name: Build, test, package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@main

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@main
    with:
      itk-python-package-org: 'BRAINSia'
      itk-python-package-tag: python_based_build_scripts
      itk-wheel-tag: 'v6.0b01'
      python3-minor-versions: '["10"]'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
